[project]
name = "project-data-exploration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Serhat Gemici", email = "serhatgemici@msn.com" },
    { name = "Ana M. Valencia Garcia", email = "dr.anamvalencia@gmail.com" },
]
requires-python = ">=3.13"
dependencies = [
    "category-encoders>=2.11.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.1",
    "seaborn>=0.13.2",
    "xlrd>=2.0.2",
]

# [project.scripts]
# jul26_bds_int_co2 = "jul26_bds_int_co2:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "nbdime>=4.0.4",
]
